[package]
name = "bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
tw-econ = { git = "https://github.com/ByFox213/tw-econ"}
async-nats = { version = "0.37.0"}
tokio = { version = "1.41.0", features = ["full"] }
log = "0.4.22"
env_logger = "0.11.5"
serde = { version = "1.0.210", features = ["derive"] }
serde_derive = "1.0.210"
serde_yaml = "0.9.33"
serde_json = "1.0.128"
futures-util = "0.3.31"
clap = { version = "4.5.20", features = ["derive"] }
once_cell = "1.20.2"
regex = "1.11.1"
liquid = "0.26.9"
futures = "0.3.31"
