server_name: Fng
message_thread_id: "1379"

nats:
  server: nats://nats:4222
  # Econ or UtilHandler
  write_path: !Single tw.econ.read.1379 # option
  read_path: # option
    !Multiple
    - tw.econ.read.1373
    - tw.econ.test.1373

  # Handler
  paths:
    - read: tw.econ.read.*
      regex:
        !Multiple
        - "\\[.*?]\\[chat]: \\d+:-?\\d+:(.*): (.*)" # trainfngChatRegex
        - "\\[.*]\\[.*]: \\*\\*\\* '(.*)' (.*)" # trainfngJoinRegex
        - "\\[chat]: \\d+:-?\\d+:(.*): (.*)" # teeworldsChatRegex
        - ".* I chat: \\d+:-?\\d+:(.*): (.*)" # ddnetChatRegex
        - ".* I chat: \\*\\*\\* '(.*?)' (.*)" # ddnetJoinRegex
      write: !Single tw.tg.{{thread_id}}
    #- read: tw.econ.read.*
    #  regex: !Single "\\[game]: leave player='\\d+:(.*)'" # teeworldsLeaveRegex
    #  write: !Single tw.tg.{{thread_id}}
    #  template: "{{text_leave}}"
    - read: tw.econ.read.*
      regex: !Single "\\[game]: team_join player='\\d+:(.*)' team=0" # teeworldsJoinRegex
      write: !Single tw.tg.{{thread_id}}
      template: "{{text_join}}"

econ:
  host: 127.0.0.1:8303
  password: econ_password
