name: Build, Push, Deploy
on:
  push:
    branches:
    - main
    - dev
jobs:
  release-docker:
    name: Release docker image
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: set NOW env
        run: echo "::set-env name=NOW::$(date +'%Y-%m-%dT%H:%M:%S')"

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: echo NOW
        run: echo "$NOW"

      - name: Log in our registry
        uses: docker/login-action@v2
        with:
          registry: d.1xxx.ru:5443
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Check out repository
      #   uses: actions/checkout@v4
      #   with:
      #     repository: octocat/my-private-repo
      #     ref: v1.0
      #     # token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      #     path: ./.github/actions/my-private-repo
      # - name: Run my action
      #   uses: ./.github/actions/my-private-repo/my-action
      #
      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     tags: siddhantkhisty/gin-kv
      #     push: true
          
      # - uses: actions-hub/kubectl@master
      #   env:
      #     KUBE_HOST: ${{ secrets.KUBE_HOST }}
      #     KUBE_CERTIFICATE: ${{ secrets.KUBE_CERTIFICATE }}
      #     KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
      #   with:
      #     args: get pods
