name: Build, Push, Deploy
on:
  push:
    branches:
    - main
    - dev
jobs:
  build:
    name: Release docker image
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: docker
    steps:
      - name: set NOW env
        run: echo "::set-env name=NOW::$(date +'%Y-%m-%dT%H:%M:%S')"

      # - name: Check out the repo
      #   uses: actions/checkout@v3

      - name: echo NOW
        run: echo "${{ env.NOW }}"

      - name: Log in our registry
        uses: docker/login-action@v2
        with:
          registry: d.1xxx.ru:5443
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
         
      # - uses: actions-hub/kubectl@master
      #   env:
      #     KUBE_HOST: ${{ secrets.KUBE_HOST }}
      #     KUBE_CERTIFICATE: ${{ secrets.KUBE_CERTIFICATE }}
      #     KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
      #   with:
      #     args: get pods
